//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHoaQua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaQua
    {
        public string Masp { get; set; }
        public string MaTH { get; set; }
        public string Tensp { get; set; }
        public string Tinhtrang { get; set; }
        public string Gia { get; set; }
        public int Soluong { get; set; }
    
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
